### PR TITLE
Data Analyses Enhansments

### PR DESCRIPTION
**Pull request by saadm2**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by saadm2** [comment]
Dear @VenturaDelMonte @jeyhunkarimov , Apologies for creating A new PR without rebasing. I

**Comment by saadm2** [comment]
I would make sure to use git command and integrate the new codes properly in the future.

**Comment by jeyhunkarimov** [comment]
@saadm2 can you please resolve conflicts in the code?

**Comment by VenturaDelMonte** [comment]
@saadm2 We tried to create a second branch for you with the conflicts solved. However, the code you submitted does not compile as we mentioned in the past. Please, be sure to submit working code. I think the best option now is:
1. you should switch to a clean and updated branch on your local environment
2. add one feature at a time, meaning you submit one tested PR with one single feature at a time

This will allow us to integrate everything faster and track changes in a timely fashion. 
I close this for now, but we look forward to your contributions.

**Pull request closed without merging**
